### ISSUE TITLE
Reorganize java files into separate folders

### ISSUE THREAD

**Issue by AaronCs** [jjtippetts/SmartLivingFinalProject#9]
I propose reorganizing the java files into separate folders. One for Models, one for ViewModels, and one for Controllers

**Comment by jjtippetts** [comment]
I agree,  it is definitely needed.

**Comment by jjtippetts** [comment]
Just finished reorganizing the files into different packages based on each repository. For example, the food controller, food repository, food exceptions, etc are all in one package. Likewise with the dietplan, meal, and user repositories. We could also further add these packages to a parent package such as nutrition to keep it separated from the exercise functionality. Let me know what you think.
